services:
  - type: web
    name: i-love-pdf-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
